name: End-to-end tests
on: [push]
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    container:
        image: memcached:1.6.15-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
