name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      cli:
      description: Run by cypress command line
      default: npm cypress run

jobs:
  cypress-electron-tests:
    steps: 
      -name: Run E2E tests
      run: ${{ github.event.inputs.cli }}
      
