name: Parallel Cypress Tests

on: [push]

jobs:
  install:
    runs-on: docker
    container:
      image: memcached:1.6.15-alpine
    steps:
      # Checkout the branch.
      - name: Checkout
        uses: actions/checkout@v2

      - name: Reclaim cache directory
        run: chown -R 1001:1001 /github/home/.cache && echo "pwn dat cache"

      # install Cypress, run lint and build
      - name: Cypress install
        uses: cypress-io/github-action@v2  # <----- This is where mine fails, when cypress is installing
        with:
          runTests: false
      - run: yarn cypress info
      - run: node -p 'os.cpus()'
      - run: yarn lint
      - run: yarn build

      # Upload build artifacts
      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: build
