on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
      memcached_server:
       image: memcached:1.6.15-alpine
    container_name: memcached_postgresql
    restart: always
    command:
      - '-m 16024 -U 0'
    ports:
      - "11211:11211"
    networks:
      - zanthus-network
    environment:
      - TZ=America/Bahia
