name: Cypress Tests

on:
  workflow_dispatch:
  
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    container:
        image: memcached:1.6.15-alpine
    
     
    steps:
              
      - name: Run E2e Tests
        run: npx cypress run

 
